// The "How far is the nearest road open to cars?" card, worked out ahead of
// time.
//
//   npm run build:streets    (node tools/build-streets.mjs; ~30 s)
//
// Writes worker/src/streets.js: for each answer, the area where a hider giving
// it can be. The Hints map keeps that area as it is, so the phone buffers
// nothing.
//
// The roads are the map's own (design/promo/round-1/lab/data/osm-campus.json,
// fetched by design/promo/round-1/tools/fetch-osm.mjs; © OpenStreetMap
// contributors, ODbL). Run it again after that file is refreshed or the campus
// border moves.
//
// Never rule out an honest hider. Two things blur the answer, so each is
// given room:
//  - What counts as a road. Streets surely do. Service roads (parking aisles,
//    driveways, delivery lanes) and tunnels may or may not, so the upper bound
//    of a band measures from every road cars use, and the lower bound only
//    from streets.
//  - The hider judges the distance by eye. An answer stretches to 1.25x its
//    upper bound plus 5 m, and its lower bound shrinks to 0.75x minus 5 m.

import { writeFileSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
// Turf comes with the worker's dev dependencies (cd worker && npm install).
const turf = createRequire(join(ROOT, "worker", "package.json"))("@turf/turf");

const OSM = join(ROOT, "design/promo/round-1/lab/data/osm-campus.json");
const BORDER = join(ROOT, "locations/geojson/campus-border.geojson");
const OUT = join(ROOT, "worker/src/streets.js");

// The answers, in metres. null: no bound on that side.
const BANDS = [
    ["Under 20 m", null, 20],
    ["20-50 m", 20, 50],
    ["50-100 m", 50, 100],
    ["Over 100 m", 100, null],
];
const stretch = (m) => m * 1.25 + 5;
const shrink = (m) => Math.max(0, m * 0.75 - 5);

const STREETS = new Set([
    "motorway", "trunk", "primary", "secondary", "tertiary",
    "motorway_link", "trunk_link", "primary_link", "secondary_link", "tertiary_link",
    "residential", "unclassified", "living_street", "road",
]);

const osm = JSON.parse(readFileSync(OSM, "utf8"));
const roads = (keep) =>
    turf.multiLineString(
        osm.features
            .filter((f) => f.geometry.type === "LineString" && f.properties.highway && keep(f.properties))
            .map((f) => f.geometry.coordinates),
    );
const anyRoad = roads((p) => STREETS.has(p.highway) || p.highway === "service");
const streets = roads((p) => STREETS.has(p.highway) && !p.tunnel);

// A little past the border, so the zones' edges never show inside the play area.
const border = JSON.parse(readFileSync(BORDER, "utf8")).features[0];
const area = turf.buffer(border, 20, { units: "meters" });

const within = (lines, m) =>
    turf.intersect(turf.featureCollection([turf.buffer(lines, m, { units: "meters", steps: 6 }), area]));

const zones = {};
for (const [answer, lower, upper] of BANDS) {
    let zone = upper === null ? area : within(anyRoad, stretch(upper));
    if (lower !== null && shrink(lower) > 0) {
        zone = turf.difference(turf.featureCollection([zone, within(streets, shrink(lower))]));
    }
    // ~2 m, then ~1 m: far inside the room each answer already has.
    zone = turf.truncate(turf.simplify(zone, { tolerance: 0.00002 }), { precision: 5 });
    zones[answer] = zone.geometry;
    console.log(`${answer}: ${(JSON.stringify(zone.geometry).length / 1024).toFixed(0)} KB`);
}

writeFileSync(
    OUT,
    `// Generated by tools/build-streets.mjs - do not edit by hand.
// For each answer to "How far is the nearest road open to cars?", the area
// where a hider giving it can be (GeoJSON geometry, [lng, lat]).
// © OpenStreetMap contributors, ODbL.

export const STREET_ZONES = ${JSON.stringify(zones)};
`,
);
console.log(`wrote ${OUT}`);
